services:
  pg:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 2s
      retries: 3

  app:
    build:
      dockerfile: docker-build/app/Dockerfile
      context: ./
    environment:
      BLOG_APP__DB__HOST: pg
      BLOG_APP__DB__DATABASE: ${DB_DATABASE}
      BLOG_APP__DB__USERNAME: ${DB_USERNAME}
      BLOG_APP__DB__PASSWORD: ${DB_PASSWORD}
      BLOG_APP__JSONPLACEHOLDER__BASE_URL: ${API_JSONPLACEHOLDER_URL}
    ports:
      - "8000:8000"
    command:
      - gunicorn
      - --workers=4
      - --worker-class=uvicorn.workers.UvicornWorker
      - --bind=0.0.0.0:8000
      - main:app
    depends_on:
      pg:
        condition: service_healthy

volumes:
  pg_data: