name: Run tests for homework

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  project-tests:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:17
        # Provide the password for postgres
        env:
          POSTGRES_DB: blog
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password_do_not_use_in_prod
        # Set health checks to wait until postgres has started
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${BLOG_APP__DB__USERNAME} -d ${BLOG_APP__DB__DATABASE}"]
          interval: 5s
          timeout: 2s
          retries: 3
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.2.1

    - name: Install dependencies
      run: poetry install --no-root

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        poetry run pytest -s -vv -r sxfE
      env:
        BLOG_APP__DB__DATABASE: blog
        BLOG_APP__DB__HOST: localhost
        BLOG_APP__DB__USERNAME: user
        BLOG_APP__DB__PASSWORD: password_do_not_use_in_prod
        SQLALCHEMY_PG_CONN_URI: postgresql+asyncpg://postgres:secretpassword@localhost:5432/postgres